

CLASSIC_AMM_SUBGRAPH = {
    "avalanche": "https://api.thegraph.com/subgraphs/name/sushiswap/exchange-avalanche",
    "arbitrum": "https://api.thegraph.com/subgraphs/name/sushiswap/exchange-arbitrum-backup",
    "bsc": "https://api.thegraph.com/subgraphs/name/sushiswap/bsc-exchange",
    "celo": "https://api.thegraph.com/subgraphs/name/sushiswap/celo-exchange",
    "ethereum": "https://api.thegraph.com/subgraphs/name/sushiswap/exchange-ethereum",
    "fantom": "https://api.thegraph.com/subgraphs/name/sushiswap/exchange-fantom",
    "fuse": "https://api.thegraph.com/subgraphs/name/sushiswap/exchange-fuse",
    "gnosis": "https://api.thegraph.com/subgraphs/name/sushiswap/xdai-exchange",
    "moonbeam": "https://api.thegraph.com/subgraphs/name/sushiswap/exchange-moonbeam",
    "moonriver": "https://api.thegraph.com/subgraphs/name/sushiswap/exchange-moonriver",
    "polygon": "https://api.thegraph.com/subgraphs/name/sushiswap/exchange-polygon",
    "harmony": "https://api.thegraph.com/subgraphs/name/sushiswap/exchange-harmony",
    "nova": "https://subgraphs.sushi.com/subgraphs/name/sushi-0m/sushiswap-arbitrum-nova",
    "boba": "https://api.thegraph.com/subgraphs/name/sushi-0m/sushiswap-boba",
}

TRIDENT_AMM_SUBGRAPH = {
    "polygon": "https://api.thegraph.com/subgraphs/name/sushi-v2/trident-polygon",
    "optimism": "https://api.thegraph.com/subgraphs/name/sushi-v2/trident-optimism",
    "kava": "https://pvt.graph.kava.io/subgraphs/name/sushi-qa/trident-kava",
    "metis": "https://andromeda.thegraph.metis.io/subgraphs/name/sushi-v2/trident-metis",
    "bttc": "https://subgraphs.sushi.com/subgraphs/name/sushi-v2/trident-bttc",
    "arbitrum": "https://api.thegraph.com/subgraphs/name/sushi-v2/trident-arbitrum",
    "bsc": "https://api.thegraph.com/subgraphs/name/sushi-v2/trident-bsc",
    "avalanche": "https://api.thegraph.com/subgraphs/name/sushi-v2/trident-avalanche",
}

V3_AMM_SUBGRAPH = {
    "ethereum": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-ethereum",
    "arbitrum": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-arbitrum",
    "base": "https://api.studio.thegraph.com/query/32073/v3-base/v0.0.1",
    "polygon": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-polygon",
    "optimism": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-optimism",
    "bsc": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-bsc",
    "thundercore": "https://graph-node.thundercore.com/subgraphs/name/sushi-v3/v3-thundercore",
    "gnosis": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-gnosis",
    "avalanche": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-avalanche",
    "fantom": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-fantom",
    "nova": "https://subgraphs.sushi.com/subgraphs/name/sushi-v3/v3-arbitrum-nova",
    #"harmony": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-harmony",
    #"metis": ,
    #"kava": ,
    #"bttc": ,
    "boba": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-boba",
    #"celo": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-celo",
    "moonriver": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-moonriver",
    "zkevm": "https://api.studio.thegraph.com/query/32073/v3-polygon-zkevm/v0.0.2",
    "core": "https://thegraph.coredao.org/subgraphs/name/sushi-v3/v3-core",
    "fuse": "https://api.thegraph.com/subgraphs/name/sushi-v3/v3-fuse",
}

ROUTE_PROCESSOR_SUBGRAPH = {
    "ethereum": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-ethereum",
    "arbitrum": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-arbitrum",
    "base": "https://api.thegraph.com/subgraphs/name/jiro-ono/routeprocessor3-base",
    "polygon": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-polygon",
    "optimism": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-optimism",
    "bsc": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-bsc",
    "thundercore": "https://graph-node.thundercore.com/subgraphs/name/sushiswap/routeprocessor3-thundercore",
    "gnosis": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-gnosis",
    "avalanche": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-avalanche",
    "fantom": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-fantom",
    "nova": "http://subgraphs.sushi.com/subgraphs/name/sushiswap/rp3-nova",
    "harmony": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-harmony",
    #"metis": ,
    #"kava": ,
    "bttc": "http://subgraphs.sushi.com/subgraphs/name/sushiswap/rp3-bttc",
    "boba": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-boba",
    "celo": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-celo",
    "moonriver": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-moonriver",
    #"zkevm": ,
    "core": "https://thegraph.coredao.org/subgraphs/name/sushiswap/routeprocessor3-core",
    "fuse": "https://api.thegraph.com/subgraphs/name/sushi-subgraphs/rp3-fuse",
}

WRAPPED_NATIVE_ADDRESS = {
    "ethereum": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
    "arbitrum": "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1",
    "base": "0x4200000000000000000000000000000000000006",
    "polygon": "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270",
    "optimism": "0x4200000000000000000000000000000000000006",
    "bsc": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
    "thundercore": "0x413cefea29f2d07b8f2acfa69d92466b9535f717",
    "gnosis": "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d",
    "avalanche": "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7",
    "fantom": "0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83",
    "nova": "0x722E8BdD2ce80A4422E880164f2079488e115365",
    "harmony": "0x796897032673ef9fcc75e4ba8667f6d88a428447",
    #"metis": ,
    #"kava": ,
    "bttc": "0x23181f21dea5936e24163ffaba4ea3b316b57f3c",
    "boba": "0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000",
    "celo": "0x471EcE3750Da237f93B8E339c536989b8978a438",
    "moonriver": "0x98878B06940aE243284CA214f92Bb71a2b032B8A",
    #"zkevm": ,
    "core": "0x40375C92d9FAf44d2f9db9Bd9ba41a3317a2404f",
    "fuse": "0x0BE9e53fd7EDaC9F859882AfdDa116645287C629",
}